{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vk.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vk.labels" . | nindent 4 }}
type: Opaque
stringData:
  adminPassword: {{ include "vk.gen" (dict "root" . "key" "adminPassword") | quote }}
  apiToken: {{ include "vk.gen" (dict "root" . "key" "apiToken") | quote }}
  sessionKey: {{ include "vk.gen" (dict "root" . "key" "sessionKey") | quote }}
  macosToken: {{ include "vk.gen" (dict "root" . "key" "macosToken") | quote }}
{{- end }}
