{{- $ha := eq (include "teleport.isHA" .) "true" -}}
{{- if and (not .Values.existingSecret) (or $ha .Values.postgresql.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teleport.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "teleport.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if $ha }}
  joinToken: {{ include "teleport.gen" (dict "root" . "key" "joinToken") | b64enc | quote }}
  {{- end }}
  {{- if .Values.postgresql.enabled }}
  postgresPassword: {{ include "teleport.gen" (dict "root" . "key" "postgresPassword") | b64enc | quote }}
  {{- end }}
{{- end }}
