{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netbird.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netbird.labels" . | nindent 4 }}
type: Opaque
data:
  authSecret: {{ include "netbird.gen" (dict "root" . "key" "authSecret") | b64enc | quote }}
  storeEncryptionKey: {{ include "netbird.gen" (dict "root" . "key" "storeEncryptionKey") | b64enc | quote }}
  sessionCookieEncryptionKey: {{ include "netbird.gen" (dict "root" . "key" "sessionCookieEncryptionKey") | b64enc | quote }}
  {{- if .Values.postgresql.enabled }}
  postgresPassword: {{ include "netbird.gen" (dict "root" . "key" "postgresPassword") | b64enc | quote }}
  {{- end }}
{{- end }}
