{{- if not .Values.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netbird.fullname" . }}-secrets
  labels:
    {{- include "netbird.labels" . | nindent 4 }}
type: Opaque
data:
  {{- /* Default PostgreSQL credentials if not provided */ -}}
  {{/*
  {{- if and .Values.postgres.enabled (not (hasKey .Values.secrets "POSTGRES_USER")) }}
  POSTGRES_USER: {{ .Values.postgres.auth.username | default "netbird" | b64enc }}
  {{- end }}
  {{- if and .Values.postgres.enabled (not (hasKey .Values.secrets "POSTGRES_PASSWORD")) }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | default (randAlphaNum 16) | b64enc }}
  {{- end }}
  {{- if and .Values.postgres.enabled (not (hasKey .Values.secrets "POSTGRES_DB")) }}
  POSTGRES_DB: {{ .Values.postgres.database | default "netbird" | b64enc }}
  {{- end }}
  
  # Automatically generate PostgreSQL URL
  {{- if and .Values.postgres.enabled (not (hasKey .Values.secrets "NETBIRD_STORE_ENGINE_POSTGRES_DSN")) }}
  NETBIRD_STORE_ENGINE_POSTGRES_DSN: {{ include "netbird.postgres.url" . | b64enc }}
  {{- end }}
  */}}
  
  {{- /* Include all user-defined secrets */ -}}
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}